import { ModelRanking, LeaderboardResponse } from '@/types/leaderboard';

const AVATAR_COLORS = [
  '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7',
  '#DDA0DD', '#98D8C8', '#F7DC6F', '#BB8FCE', '#85C1E9',
  '#F8B500', '#00CED1', '#FF69B4', '#32CD32', '#FF4500',
  '#9370DB', '#20B2AA', '#FF7F50', '#7B68EE', '#00FA9A'
];

export const mockModels: ModelRanking[] = [
  {
    model_id: 'claude-opus-4',
    model_name: 'Claude Opus 4',
    provider: 'Anthropic',
    overall_rating: 1847,
    impostor_rating: 1892,
    crewmate_rating: 1802,
    games_played: 156,
    current_rank: 1,
    previous_rank: 2,
    rank_change: 1,
    release_date: '2025-03-15',
    avatar_color: AVATAR_COLORS[0],
  },
  {
    model_id: 'gpt-5',
    model_name: 'GPT-5',
    provider: 'OpenAI',
    overall_rating: 1823,
    impostor_rating: 1856,
    crewmate_rating: 1790,
    games_played: 189,
    current_rank: 2,
    previous_rank: 1,
    rank_change: -1,
    release_date: '2025-01-20',
    avatar_color: AVATAR_COLORS[1],
  },
  {
    model_id: 'gemini-3-ultra',
    model_name: 'Gemini 3 Ultra',
    provider: 'Google',
    overall_rating: 1798,
    impostor_rating: 1834,
    crewmate_rating: 1762,
    games_played: 142,
    current_rank: 3,
    previous_rank: 3,
    rank_change: 0,
    release_date: '2025-02-28',
    avatar_color: AVATAR_COLORS[2],
  },
  {
    model_id: 'claude-sonnet-4',
    model_name: 'Claude Sonnet 4',
    provider: 'Anthropic',
    overall_rating: 1756,
    impostor_rating: 1778,
    crewmate_rating: 1734,
    games_played: 178,
    current_rank: 4,
    previous_rank: 6,
    rank_change: 2,
    release_date: '2025-03-01',
    avatar_color: AVATAR_COLORS[3],
  },
  {
    model_id: 'deepseek-v4',
    model_name: 'DeepSeek V4',
    provider: 'DeepSeek',
    overall_rating: 1742,
    impostor_rating: 1801,
    crewmate_rating: 1683,
    games_played: 134,
    current_rank: 5,
    previous_rank: 4,
    rank_change: -1,
    release_date: '2025-02-15',
    avatar_color: AVATAR_COLORS[4],
  },
  {
    model_id: 'gpt-4o',
    model_name: 'GPT-4o',
    provider: 'OpenAI',
    overall_rating: 1728,
    impostor_rating: 1745,
    crewmate_rating: 1711,
    games_played: 198,
    current_rank: 6,
    previous_rank: 5,
    rank_change: -1,
    release_date: '2024-05-13',
    avatar_color: AVATAR_COLORS[5],
  },
  {
    model_id: 'gemini-2-flash',
    model_name: 'Gemini 2.0 Flash',
    provider: 'Google',
    overall_rating: 1695,
    impostor_rating: 1712,
    crewmate_rating: 1678,
    games_played: 167,
    current_rank: 7,
    previous_rank: 8,
    rank_change: 1,
    release_date: '2024-12-11',
    avatar_color: AVATAR_COLORS[6],
  },
  {
    model_id: 'llama-4-405b',
    model_name: 'Llama 4 405B',
    provider: 'Meta',
    overall_rating: 1678,
    impostor_rating: 1723,
    crewmate_rating: 1633,
    games_played: 112,
    current_rank: 8,
    previous_rank: 10,
    rank_change: 2,
    release_date: '2025-04-01',
    avatar_color: AVATAR_COLORS[7],
  },
  {
    model_id: 'mistral-large-3',
    model_name: 'Mistral Large 3',
    provider: 'Mistral AI',
    overall_rating: 1654,
    impostor_rating: 1689,
    crewmate_rating: 1619,
    games_played: 145,
    current_rank: 9,
    previous_rank: 7,
    rank_change: -2,
    release_date: '2025-01-10',
    avatar_color: AVATAR_COLORS[8],
  },
  {
    model_id: 'qwen-3-72b',
    model_name: 'Qwen 3 72B',
    provider: 'Alibaba',
    overall_rating: 1632,
    impostor_rating: 1667,
    crewmate_rating: 1597,
    games_played: 98,
    current_rank: 10,
    previous_rank: 11,
    rank_change: 1,
    release_date: '2025-03-20',
    avatar_color: AVATAR_COLORS[9],
  },
  {
    model_id: 'grok-3',
    model_name: 'Grok 3',
    provider: 'xAI',
    overall_rating: 1618,
    impostor_rating: 1645,
    crewmate_rating: 1591,
    games_played: 87,
    current_rank: 11,
    previous_rank: 9,
    rank_change: -2,
    release_date: '2025-02-20',
    avatar_color: AVATAR_COLORS[10],
  },
  {
    model_id: 'claude-haiku-4',
    model_name: 'Claude Haiku 4',
    provider: 'Anthropic',
    overall_rating: 1589,
    impostor_rating: 1612,
    crewmate_rating: 1566,
    games_played: 176,
    current_rank: 12,
    previous_rank: 12,
    rank_change: 0,
    release_date: '2025-03-10',
    avatar_color: AVATAR_COLORS[11],
  },
  {
    model_id: 'command-r-plus-2',
    model_name: 'Command R+ 2',
    provider: 'Cohere',
    overall_rating: 1567,
    impostor_rating: 1598,
    crewmate_rating: 1536,
    games_played: 123,
    current_rank: 13,
    previous_rank: 14,
    rank_change: 1,
    release_date: '2025-01-25',
    avatar_color: AVATAR_COLORS[12],
  },
  {
    model_id: 'yi-2-large',
    model_name: 'Yi-2 Large',
    provider: '01.AI',
    overall_rating: 1545,
    impostor_rating: 1578,
    crewmate_rating: 1512,
    games_played: 89,
    current_rank: 14,
    previous_rank: 13,
    rank_change: -1,
    release_date: '2025-02-05',
    avatar_color: AVATAR_COLORS[13],
  },
  {
    model_id: 'phi-5',
    model_name: 'Phi-5',
    provider: 'Microsoft',
    overall_rating: 1523,
    impostor_rating: 1556,
    crewmate_rating: 1490,
    games_played: 156,
    current_rank: 15,
    previous_rank: 17,
    rank_change: 2,
    release_date: '2025-04-10',
    avatar_color: AVATAR_COLORS[14],
  },
  {
    model_id: 'llama-4-70b',
    model_name: 'Llama 4 70B',
    provider: 'Meta',
    overall_rating: 1498,
    impostor_rating: 1534,
    crewmate_rating: 1462,
    games_played: 134,
    current_rank: 16,
    previous_rank: 15,
    rank_change: -1,
    release_date: '2025-04-01',
    avatar_color: AVATAR_COLORS[15],
  },
  {
    model_id: 'gemma-3-27b',
    model_name: 'Gemma 3 27B',
    provider: 'Google',
    overall_rating: 1456,
    impostor_rating: 1489,
    crewmate_rating: 1423,
    games_played: 112,
    current_rank: 17,
    previous_rank: 16,
    rank_change: -1,
    release_date: '2025-03-25',
    avatar_color: AVATAR_COLORS[16],
  },
  {
    model_id: 'jamba-2',
    model_name: 'Jamba 2',
    provider: 'AI21 Labs',
    overall_rating: 1423,
    impostor_rating: 1467,
    crewmate_rating: 1379,
    games_played: 78,
    current_rank: 18,
    previous_rank: 18,
    rank_change: 0,
    release_date: '2025-02-01',
    avatar_color: AVATAR_COLORS[17],
  },
];

export function getMockLeaderboard(
  page: number = 1,
  perPage: number = 20
): LeaderboardResponse {
  const start = (page - 1) * perPage;
  const end = start + perPage;
  const paginatedData = mockModels.slice(start, end);

  return {
    data: paginatedData,
    total: mockModels.length,
    page,
    per_page: perPage,
    total_pages: Math.ceil(mockModels.length / perPage),
  };
}
