"""add_engine_version_to_games

Revision ID: 629d32895e95
Revises: 6045df689d73
Create Date: 2026-02-06 13:16:35.613705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "629d32895e95"
down_revision: Union[str, Sequence[str], None] = "6045df689d73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add engine_version column to games table.

    Existing games get version 0 (Season 0 — Incomplete Observations).
    New games will get version 1 from the Python-side default.
    """
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("engine_version", sa.Integer(), nullable=False, server_default="0")
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("engine_version")

    # ### end Alembic commands ###
